# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://berardinellidaniele.com'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: 0xBera
# Description of the Site
description: Welcome to my personal portfolio 👋
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /images/IMG_2542.gif

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: berardinellidaniele@protonmail.com
twitter_username: DanieleB13579
instagram_username: berardinellidaniele
linkedin_username: daniele-berardinelli-0a503a276/
github_username:  BerardinelliDaniele
spotify_username: 31qztybuyn4grac7bah5vz2d5wh4

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: 0xBera

# Name of the Author
author-name: Daniele Berardinelli
# URL for the Image of the Author
author-image: /images/pompompurin.png
# 60 Words About the Author
author-about: My name is Daniele Berardinelli, also known as 0xBera, I am a 17 y.o student with a strong passion for cybersecurity. I decided to create this blog to make public all the activities I do, to find a future job in the field. Every day I learn new things through CTFs (Capture The Flag), but my study does not end there. I am an enthusiast of the malware world and I enjoy analyzing them.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://www.linkedin.com/in/daniele-berardinelli-0a503a276/

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
